spring:
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DATABASE_NAME:FestivaDatabase}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

logging:
  level:
    org.telegram.telegrambots: INFO
  group:
    festiva: com.festiva
    telegram: org.telegram.telegrambots

kafka:
  enabled: ${APP_KAFKA_ENABLED:false}
  topic: festiva.bot.metric
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}
  api-key: ${KAFKA_API_KEY:}
  api-secret: ${KAFKA_API_SECRET:}
