package com.festiva.state;

public enum BotState {

    IDLE,
    WAITING_FOR_ADD_FRIEND_NAME,
    WAITING_FOR_ADD_FRIEND_DATE,
    WAITING_FOR_REMOVE_CONFIRM,
    WAITING_FOR_EDIT_NAME,
    WAITING_FOR_EDIT_DATE,
    WAITING_FOR_SEARCH
}
